version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightsail-mvc
    container_name: lightsail-php-container
    ports:
      - 80:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: lightsail
      DB_USERNAME: username
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:8.0
    container_name: lightsail-mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lightsail
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_POST: 3306
  redis:
    image: redis:4.0-alpine
    container_name: lightsail-redis-container
    ports:
      - 16379:6379
