services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: lightsail-mvc
    container_name: lightsail-php-container
    ports:
      - 80:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
    environment:
      # If you add new values below you need to restart the container, run: docker compose up -d

      DB_HOST: mysql
      DB_DATABASE: lightsail
      DB_USERNAME: username
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

      # AWS S3 settings
      AWS_BUCKET_NAME: your_aws_s3_bucket_name
      AWS_REGION: your_aws_s3_bucket_region
      AWS_VERSION: latest
      AWS_ACCESS_KEY: your_aws_access_key
      AWS_SECRET_KEY: your_aws_secret_key

      # API Tokens (for the template in Docs)
      API_TOKEN_TEMPLATE: 2aa788b32cd40c8ee0948d10f065
  mysql:
    image: mysql:8.0
    container_name: lightsail-mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lightsail
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_POST: 3306
  redis:
    image: redis:4.0-alpine
    container_name: lightsail-redis-container
    ports:
      - 6379:6379
